version: "1.0"
services:
  bot:
    build: .
    ports:
      - "3000:3000"
  datadog:
    image: "gcr.io/datadoghq/agent"
    environment:
      - DD_API_KEY=e8a1c760a2d7cd300820e56659007f0e
      - DD_APM_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_SITE=datadoghq.com
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
