version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./build.sh"
          name: build
      - run:
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./test.sh"
          name: test
      - run:
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
          name: deploy

workflows:
  version: 2
  build-project:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
